//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUIDropDownListApp.Data.Registrar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrarEntities : DbContext
    {
        public RegistrarEntities()
            : base("name=RegistrarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Personal> Personals { get; set; }
        public DbSet<Student_Misc> Student_Misc { get; set; }
        public DbSet<vw_Matri_Grad_Dates> vw_Matri_Grad_Dates { get; set; }
    }
}
